version: '3.8'

services:
    walletter-backend:
        build: ./
        command: ./wait-for-postgres.sh database ./walletter-backend -mode release
        ports:
            - 8080:8080
        depends_on:
            - database
        environment:
            - DB_PASSWORD=qwerty


    database:
        restart: unless-stopped
        image: postgres:latest
        volumes:
        - ./.database/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=qwerty
        ports:
            - 5436:5432